esphome:
  name: esphome-switchbot-hub
  friendly_name: ESPHome SwitchBot Hub
  devices:
    - id: left_curtain_device
      name: "Left Bedroom Curtain"
    - id: right_curtain_device
      name: "Right Bedroom Curtain"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "YOUR_API_KEY"

ota:
  - platform: esphome
    password: "YOUR_OTA_PASSWORD"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:

external_components:
  - source:
      type: git
      url: https://github.com/AidanMJ25/Switchbot-ESPHome-Component.git
    components: [switchbot_curtain]

cover:
  - platform: switchbot_curtain
    device_id: left_curtain_device
    id: left_bedroom_curtain
    name: "Left Bedroom Curtain"
    mac_address: "AA:BB:CC:DD:EE:FF"
    has_solar_panel: true

  - platform: switchbot_curtain
    device_id: right_curtain_device
    id: right_bedroom_curtain
    name: "Right Bedroom Curtain"
    mac_address: "11:22:33:44:55:66"
    has_solar_panel: true
